name: ForceXaeroFairPlay
version: ${version}
main: com.alfie51m.forceXaeroFairPlay.ForceXaeroFairPlay
api-version: '1.21'
folia-supported: true
permissions:
  forcexaerofairplay.bypass:
    description: Prevents the plugin from changing your minimap mode.
    default: not op